### ISSUE TITLE
Incorrect randomness claim in 50-privacy.md

### ISSUE THREAD

**Issue by dyladan** [w3c/distributed-tracing#481]
`Privacy of traceparent field` section incorrectly states that `trace-id` is randomly generated. Section should be modified such that PII in trace ids is discouraged or forbidden, and randomness suggested as a possible solution.

**Comment by kalyanaj** [comment]
Leaving this issue open to decide if we can backport this (https://github.com/w3c/trace-context/pull/482) to level-1 of the spec. 

I feel the wording in #482 ("“MUST NOT contain PII”) is sufficiently backwards compatible to backport, since the Level 1 spec *indirectly* talks about not exposing user-identifiable information.

@plehegar , based on a discussion on this in a recent working group meeting, we wanted to get your thoughts on this.

**Comment by kalyanaj** [comment]
Assigned to Philippe per our discussion in the DT working group meeting today, thanks Philippe!

**Comment by dyladan** [comment]
This is fixed in #495 but I will leave this open until it is published

**Comment by kalyanaj** [comment]
Closing this one as we have a separate issue to track republishing of level 1 spec to include this fix.
