### ISSUE TITLE
specification of lowercase is incomplete

### ISSUE THREAD

**Issue by aphillips** [w3c/distributed-tracing#506]
Header Name (also other locations)
https://www.w3.org/TR/trace-context-2/#header-name

> In order to increase interoperability across multiple protocols and encourage successful integration, by default vendors SHOULD keep the header name lowercase. The header name is a single word without any delimiters, for example, a hyphen (-).
>
> Vendors MUST expect the header name in any case (upper, lower, mixed), and SHOULD send the header name in lowercase.

The specification of "lowercase" should refer to the definitions in Infra (near [here](https://infra.spec.whatwg.org/#ascii-string)). Specifically that that the value (`traceparent`) is an "ASCII string" consisting of "ASCII alphanumeric" characters (that is, not spaces or punctuation--just letters and digits). Your SHOULD clause can then refer to "ASCII lowercase". Something like the following (although my version below may "over-explain" a bit?):

> The header name is [ASCII case-insensitive](https://infra.spec.whatwg.org/#ascii-case-insensitive). That is, `TRACEPARENT`, `TraceParent`, and `traceparent` are considered the same header. The header name is a single word containing only [ASCII alphanumeric](https://infra.spec.whatwg.org/#ascii-alphanumeric) characters; that is, it does not contain any delimiters such as a hyphen.
>
> In order to increase interoperability across multiple protocols and encourage successful integration, vendors SHOULD encode the header name as [ASCII lowercase](https://infra.spec.whatwg.org/#ascii-lowercase).

**Comment by kalyanaj** [comment]
Thanks for filing this issue. We discussed this in the DT working group meeting and we agreed on the following tweaked wording:

The header name is [ASCII case-insensitive](https://infra.spec.whatwg.org/#ascii-case-insensitive). That is, TRACEPARENT, TraceParent, and traceparent are considered the same header. The header name is a single word; it does not contain any delimiters such as a hyphen.

In order to increase interoperability across multiple protocols and encourage successful integration, tracing systems SHOULD encode the header name as [ASCII lowercase](https://infra.spec.whatwg.org/#ascii-lowercase).

**Comment by aphillips** [comment]
Thanks!! Look forward to seeing the pull request. The minor difference in your proposed wording vs. mine is not a problem. Once you have merged this change you can close this issue and I18N will be *satisfied*.

**Comment by basti1302** [comment]
PR: https://github.com/w3c/trace-context/pull/513 cc @aphillips

**Comment by aphillips** [comment]
I am _satisfied_ by this change. Thank you!
