### ISSUE TITLE
Version number relationship to ASCII and UTF-8

### ISSUE THREAD

**Issue by aphillips** [w3c/distributed-tracing#507]
3.2.2.1 version
https://www.w3.org/TR/trace-context-2/#version

> version         = 2HEXDIGLC   ; this document assumes version 00. Version ff is forbidden
>
> The value is US-ASCII encoded (which is UTF-8 compliant).
>
> Version (version) is 1 byte representing an 8-bit unsigned integer. Version ff is invalid. The current specification assumes the version is set to 00

The ABNF is `2HEXDIGLC` (which is two lowercase hex digits, e.g. \[0-9a-f\]). Mentioning US-ASCII or UTF-8 here is misleading and/or confusing, since non-ASCII characters are not permitted and EBCDIC would be unexpected 😉. It is the case that ASCII is a subset of UTF-8, but pointing this out doesn't really add anything to your spec. 

The text about the "version" being "1 byte" is also confusing, since the hex digits are two-bytes long. I would probably change your description to say:

> version         = 2HEXDIGLC   ; this document assumes version 00. Version ff is forbidden
>
> Version (`version`) is an 8-bit unsigned integer value, serialized as an ASCII string. Version `ff` is invalid. The value can be stored as a single byte. This specification assumes the version is set to 00.

**Comment by basti1302** [comment]
Thanks @aphillips for the proposed new wording. The existing wording was definitely not ideal. I took your suggestion (with minor edits) -> #511. 

We will first merge #511 to main branch and then backport it to our level-2 branch which should resolve this issue here. Feel free to take a look at the proposed new wording if you are interested.
